import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

export interface EnvVariable {
  key: string;
  value: string;
  type: 'string' | 'number' | 'boolean' | 'url' | 'email' | 'port';
  required: boolean;
  comment?: string;
}

export interface ParsedEnv {
  variables: EnvVariable[];
  typescript: string;
  zod?: string;
}

/**
 * Infer the type of an environment variable value
 */
export function inferType(value: string): EnvVariable['type'] {
  // Check for boolean
  if (/^(true|false|yes|no|1|0)$/i.test(value)) {
    return 'boolean';
  }

  // Check for number
  if (/^-?\d+(\.\d+)?$/.test(value)) {
    return 'number';
  }

  // Check for URL
  if (/^https?:\/\//i.test(value)) {
    return 'url';
  }

  // Check for email
  if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) {
    return 'email';
  }

  // Check for port (common env var patterns)
  if (/^\d{2,5}$/.test(value) && parseInt(value) <= 65535) {
    return 'port';
  }

  return 'string';
}

/**
 * Parse a .env file content
 */
export function parseEnvContent(content: string): EnvVariable[] {
  const lines = content.split('\n');
  const variables: EnvVariable[] = [];
  let lastComment: string | undefined;

  for (const line of lines) {
    const trimmed = line.trim();

    // Track comments
    if (trimmed.startsWith('#')) {
      lastComment = trimmed.slice(1).trim();
      continue;
    }

    // Skip empty lines
    if (!trimmed || !trimmed.includes('=')) {
      lastComment = undefined;
      continue;
    }

    // Parse key=value
    const eqIndex = trimmed.indexOf('=');
    const key = trimmed.slice(0, eqIndex).trim();
    let value = trimmed.slice(eqIndex + 1).trim();

    // Remove quotes
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    const type = inferType(value);
    const required = !value.startsWith('') || !!value; // Has a value = required

    variables.push({
      key,
      value,
      type,
      required: !!value,
      comment: lastComment
    });

    lastComment = undefined;
  }

  return variables;
}

/**
 * Parse a .env file
 */
export function parseEnvFile(filePath: string): EnvVariable[] {
  if (!existsSync(filePath)) {
    throw new Error(`File not found: ${filePath}`);
  }

  const content = readFileSync(filePath, 'utf-8');
  return parseEnvContent(content);
}

/**
 * Generate TypeScript interface from env variables
 */
export function generateTypeScript(variables: EnvVariable[], interfaceName: string = 'Env'): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated environment variable types',
    ' * Generated by @lxgicstudios/env-typegen',
    ' */',
    '',
    `export interface ${interfaceName} {`
  ];

  for (const v of variables) {
    const tsType = v.type === 'number' || v.type === 'port' ? 'number' :
                   v.type === 'boolean' ? 'boolean' : 'string';
    
    if (v.comment) {
      lines.push(`  /** ${v.comment} */`);
    }

    const optional = v.required ? '' : '?';
    lines.push(`  ${v.key}${optional}: ${tsType};`);
  }

  lines.push('}');
  lines.push('');

  // Generate typed getter function
  lines.push(`/**`);
  lines.push(` * Get typed environment variable`);
  lines.push(` */`);
  lines.push(`export function getEnv(): ${interfaceName} {`);
  lines.push(`  return {`);

  for (const v of variables) {
    const getter = v.type === 'number' || v.type === 'port' 
      ? `Number(process.env.${v.key})`
      : v.type === 'boolean'
      ? `['true', '1', 'yes'].includes((process.env.${v.key} || '').toLowerCase())`
      : `process.env.${v.key} || ''`;
    
    lines.push(`    ${v.key}: ${getter},`);
  }

  lines.push(`  } as ${interfaceName};`);
  lines.push(`}`);
  lines.push('');

  // Generate declaration for process.env
  lines.push('// Augment NodeJS namespace');
  lines.push('declare global {');
  lines.push('  namespace NodeJS {');
  lines.push('    interface ProcessEnv {');
  for (const v of variables) {
    const optional = v.required ? '' : '?';
    lines.push(`      ${v.key}${optional}: string;`);
  }
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('export {};');

  return lines.join('\n');
}

/**
 * Generate Zod schema from env variables
 */
export function generateZodSchema(variables: EnvVariable[], schemaName: string = 'envSchema'): string {
  const lines: string[] = [
    '/**',
    ' * Auto-generated Zod schema for environment variables',
    ' * Generated by @lxgicstudios/env-typegen',
    ' */',
    '',
    "import { z } from 'zod';",
    '',
    `export const ${schemaName} = z.object({`
  ];

  for (const v of variables) {
    let zodType: string;
    
    switch (v.type) {
      case 'number':
        zodType = 'z.string().transform(Number)';
        break;
      case 'port':
        zodType = 'z.string().transform(Number).pipe(z.number().min(1).max(65535))';
        break;
      case 'boolean':
        zodType = "z.string().transform(v => ['true', '1', 'yes'].includes(v.toLowerCase()))";
        break;
      case 'url':
        zodType = 'z.string().url()';
        break;
      case 'email':
        zodType = 'z.string().email()';
        break;
      default:
        zodType = v.required ? 'z.string().min(1)' : 'z.string().optional()';
    }

    if (v.comment) {
      lines.push(`  // ${v.comment}`);
    }
    lines.push(`  ${v.key}: ${zodType},`);
  }

  lines.push('});');
  lines.push('');
  lines.push(`export type Env = z.infer<typeof ${schemaName}>;`);
  lines.push('');
  lines.push('export function validateEnv() {');
  lines.push(`  return ${schemaName}.parse(process.env);`);
  lines.push('}');

  return lines.join('\n');
}

/**
 * Full parse and generate
 */
export function generateFromEnvFile(
  filePath: string, 
  options: { zod?: boolean; interfaceName?: string } = {}
): ParsedEnv {
  const variables = parseEnvFile(filePath);
  const typescript = generateTypeScript(variables, options.interfaceName);
  const zod = options.zod ? generateZodSchema(variables) : undefined;

  return { variables, typescript, zod };
}
